spring:
  application:
    name: java-spring
  datasource:
    url: jdbc:h2:mem:app
    driver-class-name: org.h2.Driver
    username: guilherme
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /banco-dados