spring:
  application:
    name: spring-practice
  datasource:
    url: jdbc:h2:mem:app
    driver-class-name: org.h2.Driver
    username: guilherme
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /banco-dados